### ISSUE TITLE
Render better the nomenclature listing

### ISSUE THREAD

**Issue by julbrs** [montessori-ressources/web-ui#1]
Actually we have that:

![image](https://user-images.githubusercontent.com/4988590/73769553-dd0c2700-4748-11ea-9c0e-48ffc51db225.png)

We want that:

![image](https://user-images.githubusercontent.com/4988590/73769604-f44b1480-4748-11ea-8812-cdbbd8bd09e1.png)

**Comment by analuspi** [comment]
I'm working on it. But I don't understand why GitHub is returning me a workflow error every time I push some modifications to the feature branch...

> Run failed for feature/nomenclature-list (fcb6bff)
Repository: montessori-ressources/web-ui
Workflow: CI
Duration: 57.0 seconds
Finished: 2020-02-10 15:43:26 UTC

View results

Jobs:
ca395085-040a-526b-2ce8-bdc85f692774 failed (1 annotation)

**Comment by julbrs** [comment]
Hello

My bad :D I have setup a Continuous Integration system using github Actions, and so it run the Unit Tests at each commit, and the first and only unit test is failing 😄 

I will fix that quickly, and we can have a skype tomorrow around 12pm if you want ? thanks !

**Comment by analuspi** [comment]
Ah ok :) 
I will have to confirm the skype tomorrow (I will write u a whatsapp in the morning). I'm going to the clinique sans rendez vous, so I don't know what exactly time I will be at home.

**Comment by julbrs** [comment]
I have fixed the unit test in `develop` so you can merge if you don't want to have this email at each push 😸

**Comment by analuspi** [comment]
Ah great, thanks. It was a little scary... Maybe one day u could teach me more about tests :)

**Comment by analuspi** [comment]
Hello,

I implemented react-bulma-components and I created the Card component. 
Some cards are rendering the right way:
![image](https://user-images.githubusercontent.com/37885167/74592521-2897be00-4ff0-11ea-97f9-5c2f0a218302.png)



 and others aren't:
![image](https://user-images.githubusercontent.com/37885167/74592538-5a108980-4ff0-11ea-8f54-5c00bb3e2a11.png)

Do you know why this is happening?

The code:

```
const Nomenclature = props => {
  
  return (
    <Columns>
      {props.nomenclature.cards.map(card => (
          <Card key={card._id} alt={card.originalname} src={card.location} name={props.nomenclature.name} />
      ))}
    </Columns>
  )

}
```

```
const Card = props => {
    // const TAGS = [{id:'t1', name:'pot'}] // here goes the API for tags

  return (

    <Columns.Column size="half">
      <Box>

        <span class="icon is-large is-pulled-right nomenclature-label">
          <i class="fa fa-check-circle fa-3x"></i>
        </span>

        <article class="media">
          <div class="media-left">
            <div class="thumbnails">

              <span class="tag is-rounded is-large nomenclature-image-count">
                6
              </span>

              <div class="thumbnail">
                <img src={props.src} alt={props.alt} />
              </div>
              <div class="thumbnail">
                <img src={props.src} alt={props.alt} />
              </div>
              <div class="thumbnail">
                <img src={props.src} alt={props.alt} />
              </div>
              <div class="thumbnail">
                <img src={props.src} alt={props.alt} />
              </div>
```

**Comment by julbrs** [comment]
@analuspi I get a look on that tonight. I have just checkout the branch, it look nice ! 👍

**Comment by julbrs** [comment]
Allo @analuspi the current pushed code is not exactly the same as what you put in the comments.

Just a few remarks:

1. A bit of vocabulary, are we agree on the Card and Nomenclature concept ?  Here what I am thinking of:

![image](https://user-images.githubusercontent.com/4988590/74597616-5b61a680-5030-11ea-8e14-31dcb1cd6ad5.png)

It seems that the `Card` component I see on your branch is in charge of the whole Nomenclature. I suggest to move the actual code related to the nomenclature to `nomenclature.js` and keep in `card.js` the real `Card` component ;) 

1. On my version all nomenclature are on one single row, and I think we can use two rows: don't forget to use the `Columns` component to wrap all the `Columns.Column` and set the `multiline={true}` to ` use more than one line if you add more column elements that would fit in a single row.` (*show info* link on [this page](https://couds.github.io/react-bulma-components/?path=/story/columns--basic))

```
<Columns multiline={true}>
  <Columns.Column size="half">
  // content
  </Columns.Column>
  <Columns.Column size="half">
  // content
  </Columns.Column>
  <Columns.Column size="half">
  // content
  </Columns.Column>
</Columns>
```

For example use the `Columns` component inside the `nomenclatures.js` file and the `Columns.Column` in `nomenclature.js` file.

1. I have added a task to work on header / footer #10, because it will be a good follow up after your work

Thanks for the work !

**Comment by analuspi** [comment]
Ok, thanks, I will work on the modifications.

I still have some doubts in the better way to keep my local branch updated with the remote branch (and avoid conflicts).

Usually I start with `git pull origin develop` and `git merge develop` in my feature branch.

But now I think my local feature branch is different from the remote since you did the lest push..
Is there a better way?

Have a nice sunday!

**Comment by julbrs** [comment]
Hello

I don't know... let discuss that next week !

I usually just do sometimes a `git fetch` then `git merge origin/develop` to merge the distant develop branch.

And also `git pull` when somebody commit on my branch...

**Comment by analuspi** [comment]
Ok, I've almost finished but I still have some Bulma doubts and I'm afraid that merge the pdf pull request will cause some conflicts. 
Could you do a meeting Wednesday? 

Cheers

**Comment by julbrs** [comment]
sure ! 

I have not yet merged the pdf PR so I want to let you merge bulma before the pdf PR (so I will handle the merge conflicts). I will give a check to your branch today.

Wed at lucnh time the same ?

**Comment by analuspi** [comment]
Yes, sure. 

I'm studding some Bulma today to see if I can improve the layout. I had some problems to put Columns.Colum in the JSX (it wasn't accepted).

See you wed

**Comment by julbrs** [comment]
Small tips:


in `nomenclatures.js` put the `Columns` component outside of the map (to wrap all the nomenclatures in a single `Columns` element:

```
    <Columns multiline={true}>
    {nomenclatures.map(nomenclature => (
            <Nomenclature nomenclature={nomenclature} />
        ))}
    </Columns>
```

in `nomenclature.js` don't forget the `Columns` import: 

```
import { Columns } from 'react-bulma-components'
```

then use it like that:

```
  return (
    <Columns.Column size={6}>
    <Box>
    ...
```

**Comment by analuspi** [comment]
Great, it is almost perfect. 

Except for some nomenclatures that it renders all together in one... It's weird 
![image](https://user-images.githubusercontent.com/37885167/74788604-3ebbad80-5280-11ea-9ef4-c0a87e78668f.png)

Is this any problem in the map function?

**Comment by julbrs** [comment]
Check the Card component you print 4 times the same img. 

The goal is to show only the first 4 card of the nomenclature and to show the number of cards in the white circle.

It is better and better! Keep pushing!

**Comment by julbrs** [comment]
You can use `slice` to get only the first 4 cards (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice)

**Comment by bobman38** [comment]
Linked to #6
