### ISSUE TITLE
Rework the header and the footer

### ISSUE THREAD

**Issue by julbrs** [montessori-ressources/web-ui#10]
Now we are using bulma let's clean up the header and the footer.

Let's use a [navbar](https://bulma.io/documentation/components/navbar/) for the header, and a [footer](https://bulma.io/documentation/layout/footer/) for the footer.

Let's inspire yourself with the actual app [here](https://alpha.montessori-ressources.net)

Thanks !

**Comment by analuspi** [comment]
I was thinking about build a beautiful responsive navbar with the Montessori colors... :smile:

**Comment by julbrs** [comment]
100% agree !

**Comment by julbrs** [comment]
OK all PR are merged, you can safely go on this one:

```
git checkout develop
git pull
````

to be sure to get the last commits on `develop`

and create a new feature branch (`git flow feature start xxxx`)

**Comment by analuspi** [comment]
Thanks. I'll do it soon.

**Comment by analuspi** [comment]
I did a navbar with flexbox, but I didin't like so much. So I'm changing for a bulma react component. I just need to figure out how to customize color in Bulma (because I get the exact colors from Montessori oficial site)
![navabr](https://user-images.githubusercontent.com/37885167/75169191-1f94a400-56f6-11ea-99f8-fe2dda647b22.png)

**Comment by julbrs** [comment]
Hello I think you need to follow [this](https://www.npmjs.com/package/react-bulma-components#advanced):

>  Before you use this configuration you need to setup a `_variables.sass` file somewhere in your     project (I recommend inside your src folder). This file will allow you to override bulma variables if need it like:
>  ```
>  $primary: #c3c3c3
>  ```

**Comment by julbrs** [comment]
Hello the bulma customisation is working !

<img width="742" alt="image" src="https://user-images.githubusercontent.com/4988590/75408852-0271f800-58e5-11ea-95e4-0e35bb516aa2.png">

I have push a commit on your branch ;)

**Comment by analuspi** [comment]
Nice! Thanks! What was the problem?

**Comment by julbrs** [comment]
Hello the commit is [here](https://github.com/montessori-ressources/web-ui/commit/54ea2384b5e45aedb607f555527304869d9059ca), and what I have changed:

* switch content between `App.scss` and `_variables.sass`
* import the right sass file in `App.scss` (`~react-bulma-components/src/index.sass`)
* instead of importing react bulma component like that: `import { Navbar } from 'react-bulma-components'` now do that: `import Navbar from 'react-bulma-components/lib/components/navbar'`

And magically it work... But the most important is the last bullet, the way we use to import component is not compatible with the SASS customization I think !

I let you customize ;)
