### ISSUE TITLE
Card count must be correct

### ISSUE THREAD

**Issue by julbrs** [montessori-ressources/web-ui#21]
On nomenclature list the card count must show the number of cards

<img width="773" alt="image" src="https://user-images.githubusercontent.com/4988590/75610508-ab844280-5adf-11ea-8765-54e3cfa896d2.png">

Here it show 6 but it must show 1 because there is only one card/image in this case.

**Comment by JohnRawlins** [comment]
Can I work on this issue?

**Comment by julbrs** [comment]
> Can I work on this issue?

Sure ! I will be happy to review a PR !

Thanks !

**Comment by julbrs** [comment]
@JohnRawlins thanks !
