### ISSUE TITLE
Replace fetch() calls by axios call

### ISSUE THREAD

**Issue by julbrs** [montessori-ressources/web-ui#28]

**Comment by analuspi** [comment]
Why we need to replace?

**Comment by julbrs** [comment]
Good question :D 

I have started to replace fetch() by axios when working on the facebook auth because I wasn't able to make it work with fetch...

**Comment by analuspi** [comment]
Ok. For me is better, since I just know axios.

**Comment by julbrs** [comment]
axios is easier to use...
