### ISSUE TITLE
Finish a google auth button like the Facebook one

### ISSUE THREAD

**Issue by julbrs** [montessori-ressources/web-ui#30]
Actually we can connect using FB. 

Can we do the same with Google ? check the package `react-google-login` to generate the google link.

**Comment by analuspi** [comment]
Should I start this one?

**Comment by julbrs** [comment]
Hello,

yes I let you this part ! social auth is fun ;)

**Comment by analuspi** [comment]
Ok, I will start tomorrow in a new branch . :)
