### ISSUE TITLE
Check if we can generate a pdf directly on React

### ISSUE THREAD

**Issue by julbrs** [montessori-ressources/web-ui#4]
Instead of having a endpoint that send a pdf, can we generate the pdf locally in React ?

**Comment by julbrs** [comment]
check [react-to-print](https://www.npmjs.com/package/react-to-print) 

it avoid pdf generation.

or if we want pdf generation i have [pdfjs](https://www.npmjs.com/package/pdfjs)

**Comment by julbrs** [comment]
* react-to-print not a good choice because we can't force to print in landscape
* new option [react-pdf](https://github.com/diegomura/react-pdf)
* pdfjs not easy to use in react components ?

**Comment by julbrs** [comment]
Working on react-pdf seems the best choice.

For info @analuspi  I am also implementing `react-router` in my branch, hope that you have not yet worked on this part 😄

**Comment by analuspi** [comment]
No, I'm still working on Bulma, but please leave some react features for me too :smile:
