### ISSUE TITLE
Not possible to login on google anymore :D

### ISSUE THREAD

**Issue by julbrs** [montessori-ressources/web-ui#42]
Because `facebookId` must be unique event on google account and null is not unique !

**Comment by julbrs** [comment]
@analuspi I have updated the backend can you test to login again ?

thanks !

**Comment by analuspi** [comment]
I tried and it still isn't working :cry: 
![image](https://user-images.githubusercontent.com/37885167/77563867-387caa80-6e98-11ea-9bed-3237dfd96a6b.png)
![image](https://user-images.githubusercontent.com/37885167/77564030-7b3e8280-6e98-11ea-9ca2-8190dedb26fd.png)

**Comment by julbrs** [comment]
Hello it must work now ;)

**Comment by analuspi** [comment]
It works! Thanks!

**Comment by julbrs** [comment]
Let's close that ;)
