### ISSUE TITLE
Rethink the admin painel for mobile devices

### ISSUE THREAD

**Issue by analuspi** [montessori-ressources/web-ui#56]
Currently the admin page doesn't fit in the mobile viewport: 

![image](https://user-images.githubusercontent.com/37885167/81121724-6a544880-8efd-11ea-8abb-b75fa1f15125.png)

Should we resize or think about a compact version?

**Comment by julbrs** [comment]
Hum I am not agree: the admin panel is created via _react-admin_ and it is not in first task to redesign it.

Let's focus on the other part of the interface that we are managing our-self ?

**Comment by analuspi** [comment]
Ok, no problem.
