### ISSUE TITLE
If issue during nomenclature creation then no warning

### ISSUE THREAD

**Issue by julbrs** [montessori-ressources/web-ui#63]
We must advise the user that an issue has occured during the nomenclature creation.

I am suggesting to add a notification if there is an issue, like the one we can see in admin panel:

![image](https://user-images.githubusercontent.com/4988590/86822730-ff88d000-c059-11ea-87dc-ef4a49d63709.png)

Take for example the case #62

**Comment by analuspi** [comment]
Should I create a new state? 

For example:
`const[error, setError] = useState(null)`

And add a new condition at renderActions?
```
const renderActions = () => {
if (error) {
return "oh no!"
}
```

**Comment by julbrs** [comment]
Hello 

yes it seems to be a good idea !
